# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: company.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rcompany.proto\x12\x07\x63ompany\"\x1f\n\x11GetCompanyRequest\x12\n\n\x02id\x18\x01 \x01(\t\"\xd8\x02\n\x12GetCompanyResponse\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0e\n\x06userId\x18\x02 \x01(\t\x12\x13\n\x0b\x63ompanyName\x18\x03 \x01(\t\x12\x0e\n\x06street\x18\x04 \x01(\t\x12\x18\n\x10streetAdditional\x18\x05 \x01(\t\x12\x12\n\npostalCode\x18\x06 \x01(\t\x12\x0c\n\x04\x63ity\x18\x07 \x01(\t\x12\x0c\n\x04iban\x18\x08 \x01(\t\x12\x0b\n\x03\x62ic\x18\t \x01(\t\x12\x1a\n\x12registrationNumber\x18\n \x01(\t\x12\x10\n\x08vatPayer\x18\x0b \x01(\x08\x12\r\n\x05vatId\x18\x0c \x01(\t\x12\x16\n\x0e\x61\x64\x64itionalInfo\x18\r \x01(\t\x12\x18\n\x10\x64ocumentLocation\x18\x0e \x01(\t\x12\x15\n\rreverseCharge\x18\x0f \x01(\x08\x12\x11\n\tcreatedAt\x18\x10 \x01(\t\x12\x11\n\tupdatedAt\x18\x11 \x01(\t2W\n\x0e\x43ompanyService\x12\x45\n\nGetCompany\x12\x1a.company.GetCompanyRequest\x1a\x1b.company.GetCompanyResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'company_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_GETCOMPANYREQUEST']._serialized_start=26
  _globals['_GETCOMPANYREQUEST']._serialized_end=57
  _globals['_GETCOMPANYRESPONSE']._serialized_start=60
  _globals['_GETCOMPANYRESPONSE']._serialized_end=404
  _globals['_COMPANYSERVICE']._serialized_start=406
  _globals['_COMPANYSERVICE']._serialized_end=493
# @@protoc_insertion_point(module_scope)
